/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reciclado;

import Reciclado.dao.ChoferDao;
import Reciclado.dao.ClienteDAO;
import Reciclado.dao.PlantaDao;
import Reciclado.dao.ResiduoDao;
import Reciclado.dao.SolicitudDao;
import Reciclado.dao.VehiculoDao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author Rafa
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /*Modelo de tabla*/
    DefaultTableModel defaultTableModel;
    //datos INICIALMENTE VACIO
    String data[][]={};
    
    //cabezera de tabla inicialmente con los nombre de columnas
    String cabezera[]={"id_solicitud","id_cliente","NOMBRE","RUT","EMAIL","DIRECCION","TIPO DOMICILIO","CIUDAD","KILOGRAMOS","PRECIO"};
    
    
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        
        //se inicia el listados de datos precargados
        listarPlantas();
        listarChoferes();
        listarVehiculos();
        listarResiduos();
        listarSolicitudesEnTabla();
        
        
        //MANIPULAR COLUMNAS DE TABLA, SETEAR EL ANCHO EN 0 PARA LOS IDS OCULTOS
        TableColumn columnaIdSolicitud = tablaSolicitud.getColumn("id_solicitud");
        TableColumn columnaIdCliente = tablaSolicitud.getColumn("id_cliente");
        columnaIdSolicitud.setMinWidth(0);
        columnaIdSolicitud.setMaxWidth(0);
        columnaIdCliente.setMinWidth(0);
        columnaIdCliente.setMaxWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboPlanta = new javax.swing.JComboBox<>();
        comboChofer = new javax.swing.JComboBox<>();
        comboVehiculo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        textoRut = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JTextField();
        textoTipoDomicilio = new javax.swing.JTextField();
        textoCiudad = new javax.swing.JTextField();
        textoKilogramos = new javax.swing.JTextField();
        textoPrecio = new javax.swing.JTextField();
        botonCrearSolicitud = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitud = new javax.swing.JTable();
        comboResiduo = new javax.swing.JComboBox<>();
        botonActualizarSolicitud = new javax.swing.JButton();
        botonEliminarSolicitud = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mCordinacion = new javax.swing.JMenuItem();
        mCliente = new javax.swing.JMenuItem();
        mChofer = new javax.swing.JMenuItem();
        mPlanta = new javax.swing.JMenuItem();
        mSolicitud = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIÓN DE RECOLECCIÓN DE RESIDUOS");

        jLabel2.setText("nombre cliente");

        jLabel3.setText("rut");

        jLabel4.setText("email");

        jLabel5.setText("direccion");

        jLabel6.setText("tipo domicilio");

        jLabel7.setText("ciudad");

        jLabel8.setText("tipo residuo");

        jLabel9.setText("kilogramos");

        jLabel10.setText("precio");

        jLabel11.setText("planta");

        jLabel12.setText("chofer");

        jLabel13.setText("vehiculo");

        textoKilogramos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoKilogramosKeyTyped(evt);
            }
        });

        textoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoPrecioKeyTyped(evt);
            }
        });

        botonCrearSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonCrearSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonCrearSolicitud.setText("Crear Solicitud");
        botonCrearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearSolicitudActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        tablaSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tablaSolicitud.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitud);

        botonActualizarSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonActualizarSolicitud.setText("Actualizar Solicitud");
        botonActualizarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSolicitudActionPerformed(evt);
            }
        });

        botonEliminarSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonEliminarSolicitud.setText("Eliminar Solicitud");
        botonEliminarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoNombreCliente)
                                    .addComponent(textoRut)
                                    .addComponent(textoEmail)
                                    .addComponent(textoDireccion)
                                    .addComponent(textoTipoDomicilio)
                                    .addComponent(textoCiudad))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonActualizarSolicitud)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarSolicitud)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboPlanta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textoKilogramos, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textoPrecio)
                                        .addComponent(comboResiduo, 0, 257, Short.MAX_VALUE))))
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(53, 53, 53))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textoKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textoTipoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(comboPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonActualizarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu.setText("Menú");
        menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        mCordinacion.setText("Coordinación");
        mCordinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCordinacionActionPerformed(evt);
            }
        });
        menu.add(mCordinacion);

        mCliente.setText("Mostrar Clientes");
        mCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClienteActionPerformed(evt);
            }
        });
        menu.add(mCliente);

        mChofer.setText("Mostar Choferes");
        mChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mChoferActionPerformed(evt);
            }
        });
        menu.add(mChofer);

        mPlanta.setText("Mostar Plantas");
        menu.add(mPlanta);

        mSolicitud.setText("Mostar Solicitud");
        menu.add(mSolicitud);
        menu.add(jSeparator1);

        mSalir.setText("Salir");
        menu.add(mSalir);

        barraMenu.add(menu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCordinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCordinacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCordinacionActionPerformed

    private void mClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mClienteActionPerformed

    private void mChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mChoferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mChoferActionPerformed

    private void botonCrearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearSolicitudActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNombreCliente(textoNombreCliente.getText());
        cliente.setRutCliente(textoRut.getText());
        cliente.setEmail(textoEmail.getText());
        cliente.setDireccion(textoDireccion.getText());
        cliente.setTipoDomicilio(textoTipoDomicilio.getText());
        cliente.setCiudad(textoCiudad.getText());

        //guardar cliente
        ClienteDAO clienteDao = new ClienteDAO();
        int id = clienteDao.agregarCliente(cliente);
        
        
        Solicitud solicitud = new Solicitud();
        solicitud.setIdCliente(id);
        solicitud.setCiudadSolicitud(textoCiudad.getText().toString());
        solicitud.setTipoResiduo(comboResiduo.getSelectedItem().toString());
        solicitud.setKilogramos(Integer.parseInt(textoKilogramos.getText().equals("") ? "0" : textoKilogramos.getText()));
        solicitud.setPrecio(Integer.parseInt(textoPrecio.getText().equals("") ? "0" : textoPrecio.getText()));
        
        //guardar solicitud
        SolicitudDao solicitudDAO = new SolicitudDao();
        solicitudDAO.agregarSolicitud(solicitud);
        
        //reset
        String fila[] = new  String[cabezera.length];
        //nombre
        fila[2] =  textoNombreCliente.getText().toString();
        //rut
        fila[3] =  textoRut.getText().toString();
        //email
        fila[4] =  textoEmail.getText().toString();
        //direccion
        fila[5] =  textoDireccion.getText().toString();
        //tipo domicilio
        fila[6] =  textoTipoDomicilio.getText().toString();
        //ciudad
        fila[7] =  comboResiduo.getSelectedItem().toString();
        //kilogramos
        fila[8] =  textoKilogramos.getText().toString();
        //precio
        fila[9] =  textoPrecio.getText().toString();
        
        
        //agrega la fila (fila[]) a la tabla
        defaultTableModel.addRow(fila);
        //se agrega el modelo a la tabla
        tablaSolicitud.setModel(defaultTableModel);
        //limpia el formulario
        limpiarFormulario();
        //hace un refresh de la tabla para mostrar lo ultimo de la informacion
        listarSolicitudesEnTabla();
    }//GEN-LAST:event_botonCrearSolicitudActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void textoKilogramosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKilogramosKeyTyped
        txfSoloNumeros(evt, textoKilogramos);
    }//GEN-LAST:event_textoKilogramosKeyTyped

    private void textoPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoPrecioKeyTyped
        txfSoloNumeros(evt, textoPrecio);
    }//GEN-LAST:event_textoPrecioKeyTyped

    private void tablaSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudMouseClicked
       //DELO MODELO DE LA TABLA OBTENER TODOS LOS VALORES
        String nombre = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 2).toString();
        String rut = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 3).toString();
        String email = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 4).toString();
        String direccion = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 6).toString();
        String tipoDomicilio = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 6).toString();
        String ciudad = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 7).toString();
        String kilogramos = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 8).toString();
        String precio = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 9).toString();
        
        textoNombreCliente.setText(nombre);
        textoRut.setText(rut);
        textoEmail.setText(email);
        textoDireccion.setText(direccion);
        textoTipoDomicilio.setText(tipoDomicilio);
        textoCiudad.setText(ciudad);
        textoKilogramos.setText(kilogramos);
        textoPrecio.setText(precio);
    }//GEN-LAST:event_tablaSolicitudMouseClicked

    private void botonActualizarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSolicitudActionPerformed
        if(tablaSolicitud.getSelectedRowCount()==1){
            int idSolicitudOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 0).toString());
            int idClienteOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 1).toString());
            String rutOlder = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 2).toString();
            String nombre = textoNombreCliente.getText();
            String rut = textoRut.getText();
            String email = textoEmail.getText();
            String direccion = textoDireccion.getText();
            String tipoDomicilio = textoTipoDomicilio.getText();
            String ciudad = textoCiudad.getText();
            String kilogramos = textoKilogramos.getText();
            String precio = textoPrecio.getText();
            
            //guardar en base de datos
            Cliente cliente = new Cliente();
            cliente.setNombreCliente(nombre);
            cliente.setRutCliente(rut);
            cliente.setEmail(email);
            cliente.setDireccion(direccion);
            cliente.setTipoDomicilio(tipoDomicilio);
            cliente.setCiudad(ciudad);

            //guardar cliente
            ClienteDAO clienteDao = new ClienteDAO();
            clienteDao.actualizarCliente(rutOlder,cliente);


            Solicitud solicitud = new Solicitud();
            solicitud.setIdCliente(idClienteOlder);
            solicitud.setKilogramos(Integer.parseInt(kilogramos.equals("") ? "0" : textoKilogramos.getText()));
            solicitud.setPrecio(Integer.parseInt(precio.equals("") ? "0" : textoPrecio.getText()));
            
            //guardar solicitud
            SolicitudDao solicitudDAO = new SolicitudDao();
            solicitudDAO.actualizarSolicitud(idSolicitudOlder, solicitud);
            
            //actulizar tabla (grilla)
            defaultTableModel.setValueAt(idSolicitudOlder, tablaSolicitud.getSelectedRow(), 0);
            defaultTableModel.setValueAt(idClienteOlder, tablaSolicitud.getSelectedRow(), 1);
            defaultTableModel.setValueAt(nombre, tablaSolicitud.getSelectedRow(), 2);
            defaultTableModel.setValueAt(rut, tablaSolicitud.getSelectedRow(), 3);
            defaultTableModel.setValueAt(email, tablaSolicitud.getSelectedRow(), 4);
            defaultTableModel.setValueAt(direccion, tablaSolicitud.getSelectedRow(), 5);
            defaultTableModel.setValueAt(tipoDomicilio, tablaSolicitud.getSelectedRow(), 6);
            defaultTableModel.setValueAt(ciudad, tablaSolicitud.getSelectedRow(), 7);
            defaultTableModel.setValueAt(kilogramos, tablaSolicitud.getSelectedRow(), 8);
            defaultTableModel.setValueAt(precio, tablaSolicitud.getSelectedRow(), 9);
        }
    }//GEN-LAST:event_botonActualizarSolicitudActionPerformed

    private void botonEliminarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSolicitudActionPerformed
        if(tablaSolicitud.getSelectedRowCount()==1){
            int idSolicitudOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 0).toString());
            //eliminar desde la base de datos
            SolicitudDao solicitudDao = new SolicitudDao();
            solicitudDao.eliminarSolicitud(idSolicitudOlder);
            //REMOVER FILA DE LA TABLA (grilla)
            defaultTableModel.removeRow(tablaSolicitud.getSelectedRow());
        }
    }//GEN-LAST:event_botonEliminarSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonActualizarSolicitud;
    private javax.swing.JButton botonCrearSolicitud;
    private javax.swing.JButton botonEliminarSolicitud;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JComboBox<Object> comboChofer;
    private javax.swing.JComboBox<Object> comboPlanta;
    private javax.swing.JComboBox<Object> comboResiduo;
    private javax.swing.JComboBox<Object> comboVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mChofer;
    private javax.swing.JMenuItem mCliente;
    private javax.swing.JMenuItem mCordinacion;
    private javax.swing.JMenuItem mPlanta;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mSolicitud;
    private javax.swing.JMenu menu;
    private javax.swing.JTable tablaSolicitud;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoKilogramos;
    private javax.swing.JTextField textoNombreCliente;
    private javax.swing.JTextField textoPrecio;
    private javax.swing.JTextField textoRut;
    private javax.swing.JTextField textoTipoDomicilio;
    // End of variables declaration//GEN-END:variables

    private void listarResiduos() {
        ResiduoDao resisuoDao = new ResiduoDao();
        HashMap<Integer,String> residuos = new HashMap();
        residuos = resisuoDao.obtenerResiduos();
        for (String value : residuos.values()) {
            //se agrega al componente grafico combobox de residuos
            comboResiduo.addItem(value);
        }
    }
    private void listarPlantas() {
        PlantaDao plantaDao = new PlantaDao();
        HashMap<Integer,String> plantas = new HashMap();
        plantas = plantaDao.obtenerPlantas();
        for (String value : plantas.values()) {
            //se agrega al componente grafico combobox de plantas
            comboPlanta.addItem(value);
        }
    }
    private void listarChoferes() {
        ChoferDao choferDao = new ChoferDao();
        HashMap<Integer,String> choferes = new HashMap();
        choferes = choferDao.obtenerChoferes();
        for (String value : choferes.values()) {
            //se agrega al componente grafico combobox de Choferes
            comboChofer.addItem(value);
        }
    }
    private void listarVehiculos() {
        VehiculoDao vehiculoDao = new VehiculoDao();
        HashMap<Integer,String> vehiculos = new HashMap();
        vehiculos = vehiculoDao.obtenerVehiculos();
        for (String value : vehiculos.values()) {
            //se agrega al componente grafico combobox de vehiculos
            comboVehiculo.addItem(value);
        }
    }
    
    private void limpiarFormulario(){
        textoCiudad.setText("");
        textoDireccion.setText("");
        textoEmail.setText("");
        textoKilogramos.setText("");
        textoNombreCliente.setText("");
        textoPrecio.setText("");
        textoRut.setText("");
        textoTipoDomicilio.setText("");
    }
    
    private void txfSoloNumeros(java.awt.event.KeyEvent evt,JTextField txf){
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
            (caracter != KeyEvent.VK_BACK_SPACE) &&
            (caracter != '.'))
        {
            evt.consume();  // ignorar el evento de teclado
        }
         if(txf.getText().length()>9)
             evt.consume();
    }

    private void listarSolicitudesEnTabla() {
        this.defaultTableModel = new DefaultTableModel(data, cabezera);
        SolicitudDao solicitudDao = new SolicitudDao();
        ResultSet result = solicitudDao.listarSolicitudes();
        try { 
            while(result.next()){
                Object[] fila=new Object[cabezera.length];//array sera una de las filas de la tabla
                for(int i=0;i<cabezera.length;i++){          
                    fila[i]=result.getObject(i+1);
                }
                defaultTableModel.addRow(fila);  
            } 
            tablaSolicitud.setModel(defaultTableModel);
        } catch (SQLException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
