/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reciclado.ventanas;

import Reciclado.Chofer;
import Reciclado.Cliente;
import Reciclado.Planta;
import Reciclado.Residuo;
import Reciclado.Solicitud;
import Reciclado.Vehiculo;
import Reciclado.abstrac.AbstractEmpleado;
import Reciclado.abstrac.IActivo;
import Reciclado.dao.ClienteDAO;
import Reciclado.dao.Database;
import Reciclado.dao.MysqlDatabase;
import Reciclado.dao.SolicitudDao;
import Reciclado.ventanaPrincipal;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Fernando Sancho
 */
public class VentanaEditorSolicitudes extends javax.swing.JInternalFrame {

    /*Modelo de tabla*/
    DefaultTableModel defaultTableModel;
    //datos INICIALMENTE VACIO
    String data[][]={};
    
    //cabezera de tabla inicialmente con los nombre de columnas
    String cabezera[]={"id_solicitud","id_cliente","NOMBRE","RUT","EMAIL","DIRECCION","TIPO DOMICILIO","CIUDAD","KILOGRAMOS","PRECIO"};
    
    //ESTRUCTURAS
    List<Cliente> listaSolicitudesClientes  = new ArrayList<>();
    List<Cliente> listaClientes  = new ArrayList<>();
    
    
   Cliente clienteSelected  = new Cliente();
   Solicitud solicitudSelected  = new Solicitud();
    
   
   Database database;
    SolicitudDao daoSolicitud;
    ClienteDAO clienteDao;
    
    public VentanaEditorSolicitudes() {
    }

    public VentanaEditorSolicitudes(List<Cliente> listaClientes, List<Cliente> listaSolicitudesClientes) {
        initComponents();
        this.database = new MysqlDatabase();
        this.daoSolicitud = new SolicitudDao(database);
        this.clienteDao = new ClienteDAO(database); 
        this.listaSolicitudesClientes = listaSolicitudesClientes;
        this.listaClientes = listaClientes;
        //se inicia el listados de datos precargados
        listarPlantas();
        listarChoferes();
        listarVehiculos();
        listarResiduos();
        listarSolicitudesEnTabla();
        //MANIPULAR COLUMNAS DE TABLA, SETEAR EL ANCHO EN 0 PARA LOS IDS OCULTOS
        TableColumn columnaIdSolicitud = tablaSolicitud.getColumn("id_solicitud");
        TableColumn columnaIdCliente = tablaSolicitud.getColumn("id_cliente");
        columnaIdSolicitud.setMinWidth(0);
        columnaIdSolicitud.setMaxWidth(0);
        columnaIdCliente.setMinWidth(0);
        columnaIdCliente.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCrearSolicitud = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonActualizarSolicitud = new javax.swing.JButton();
        botonEliminarSolicitud = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textoDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoTipoDomicilio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoCiudad = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        textoNombreCliente = new javax.swing.JTextField();
        textoRut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboResiduo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textoKilogramos = new javax.swing.JTextField();
        textoPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboVehiculo = new javax.swing.JComboBox<>();
        comboChofer = new javax.swing.JComboBox<>();
        comboPlanta = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        precioCalculoText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ivaText = new javax.swing.JTextField();
        totalPagarText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitud = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIÓN DE RECOLECCIÓN DE RESIDUOS");

        botonCrearSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonCrearSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonCrearSolicitud.setText("Crear Solicitud");
        botonCrearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearSolicitudActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonActualizarSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonActualizarSolicitud.setText("Actualizar Solicitud");
        botonActualizarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSolicitudActionPerformed(evt);
            }
        });

        botonEliminarSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarSolicitud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonEliminarSolicitud.setText("Eliminar Solicitud");
        botonEliminarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSolicitudActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        jPanel2.setName(""); // NOI18N

        jLabel5.setText("direccion");

        jLabel6.setText("tipo domicilio");

        jLabel7.setText("ciudad");

        textoNombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoNombreClienteFocusLost(evt);
            }
        });

        textoRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoRutFocusLost(evt);
            }
        });

        jLabel3.setText("rut");

        jLabel2.setText("nombre cliente");

        jLabel4.setText("email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78)
                        .addComponent(textoEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textoRut, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
                            .addComponent(textoNombreCliente))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoTipoDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(textoCiudad)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDireccion)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(textoTipoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Solicitud"));

        jLabel8.setText("tipo residuo");

        jLabel9.setText("kilogramos");

        textoKilogramos.setToolTipText("");
        textoKilogramos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoKilogramos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoKilogramosKeyTyped(evt);
            }
        });

        textoPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoPrecioFocusLost(evt);
            }
        });
        textoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoPrecioKeyTyped(evt);
            }
        });

        jLabel10.setText("precio");

        jLabel11.setText("planta");

        jLabel12.setText("chofer");

        jLabel13.setText("vehiculo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(45, 45, 45)
                        .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(comboResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboPlanta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textoKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(comboPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLabel14.setText("Precio");

        precioCalculoText.setEditable(false);
        precioCalculoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCalculoTextActionPerformed(evt);
            }
        });

        jLabel15.setText("IVA");

        jLabel16.setText("Total a pagar:");

        ivaText.setEditable(false);
        ivaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaTextActionPerformed(evt);
            }
        });

        totalPagarText.setEditable(false);
        totalPagarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPagarTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(precioCalculoText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(ivaText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPagarText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioCalculoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ivaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPagarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tablaSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tablaSolicitud.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitud);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizarSolicitud)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarSolicitud)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonActualizarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoKilogramosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKilogramosKeyTyped
        txfSoloNumeros(evt, textoKilogramos);
    }//GEN-LAST:event_textoKilogramosKeyTyped

    private void textoPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoPrecioKeyTyped
        txfSoloNumeros(evt, textoPrecio);
    }//GEN-LAST:event_textoPrecioKeyTyped

    private void botonCrearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearSolicitudActionPerformed

        boolean existe = clienteExiste();
        if(existe){
            JOptionPane.showMessageDialog(this, "Cliente "+textoNombreCliente.getText()+" ya existe");
            return;
        }
        
        
        boolean existeSolicitud = solicitudExisteParaCliente();
        if(existeSolicitud){
            JOptionPane.showMessageDialog(this, "Cliente  "+textoNombreCliente.getText()+" ya existe en solicitud");
            return;
        }

        
        Cliente cliente = new Cliente();
        cliente.setNombreCliente(textoNombreCliente.getText());
        cliente.setRutCliente(textoRut.getText());
        cliente.setEmail(textoEmail.getText());
        cliente.setDireccion(textoDireccion.getText());
        cliente.setTipoDomicilio(textoTipoDomicilio.getText());
        cliente.setCiudad(textoCiudad.getText());
        
        //guardar cliente
        
        int id = clienteDao.agregarCliente(cliente);

        Solicitud solicitud = new Solicitud();
        solicitud.setIdCliente(id);
        solicitud.setCiudadSolicitud(textoCiudad.getText().toString());
        solicitud.setTipoResiduo(comboResiduo.getSelectedItem().toString());
        solicitud.setKilogramos(Integer.parseInt(textoKilogramos.getText().equals("") ? "0" : String.valueOf(Math.round(Float.parseFloat(textoKilogramos.getText())))));
        solicitud.setPrecio(Integer.parseInt(textoPrecio.getText().equals("") ? "0" : String.valueOf(Math.round(Float.parseFloat(textoPrecio.getText())))));

        //guardar solicitud
        
        daoSolicitud.agregarSolicitud(solicitud);
        

        //reset
        String fila[] = new  String[cabezera.length];
        //nombre
        fila[2] =  textoNombreCliente.getText().toString();
        //rut
        fila[3] =  textoRut.getText().toString();
        //email
        fila[4] =  textoEmail.getText().toString();
        //direccion
        fila[5] =  textoDireccion.getText().toString();
        //tipo domicilio
        fila[6] =  textoTipoDomicilio.getText().toString();
        //ciudad
        fila[7] =  comboResiduo.getSelectedItem().toString();
        //kilogramos
        fila[8] =  textoKilogramos.getText().toString();
        //precio
        fila[9] =  textoPrecio.getText().toString();

        //agrega la fila (fila[]) a la tabla
        defaultTableModel.addRow(fila);
        //se agrega el modelo a la tabla
        tablaSolicitud.setModel(defaultTableModel);
        //limpia el formulario
        limpiarFormulario();
        //hace un refresh de la tabla para mostrar lo ultimo de la informacion
        listarSolicitudesEnTabla();
    }//GEN-LAST:event_botonCrearSolicitudActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void tablaSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudMouseClicked
        //DELO MODELO DE LA TABLA OBTENER TODOS LOS VALORES
        String nombre = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 2).toString();
        String rut = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 3).toString();
        String email = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 4).toString();
        String direccion = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 6).toString();
        String tipoDomicilio = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 6).toString();
        String ciudad = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 7).toString();
        String kilogramos = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 8).toString();
        String precio = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 9).toString();

        textoNombreCliente.setText(nombre);
        textoRut.setText(rut);
        textoEmail.setText(email);
        textoDireccion.setText(direccion);
        textoTipoDomicilio.setText(tipoDomicilio);
        textoCiudad.setText(ciudad);
        textoKilogramos.setText(kilogramos);
        textoPrecio.setText(precio);
        
//        this.obtenerClienteSelected();
//        this.obtenerSolicitudSelected();
        this.calcularPrecioFinal();
    }//GEN-LAST:event_tablaSolicitudMouseClicked

    private void botonActualizarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSolicitudActionPerformed
        if(tablaSolicitud.getSelectedRowCount()==1){
            int idSolicitudOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 0).toString());
            int idClienteOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 1).toString());
            String rutOlder = defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 2).toString();
            String nombre = textoNombreCliente.getText();
            String rut = textoRut.getText();
            String email = textoEmail.getText();
            String direccion = textoDireccion.getText();
            String tipoDomicilio = textoTipoDomicilio.getText();
            String ciudad = textoCiudad.getText();
            String kilogramos = textoKilogramos.getText();
            String precio = textoPrecio.getText();

            //guardar en base de datos
            Cliente cliente = new Cliente();
            cliente.setNombreCliente(nombre);
            cliente.setRutCliente(rut);
            cliente.setEmail(email);
            cliente.setDireccion(direccion);
            cliente.setTipoDomicilio(tipoDomicilio);
            cliente.setCiudad(ciudad);
            
            //guardar cliente
            clienteDao.actualizarCliente(rutOlder,cliente);

            Solicitud solicitud = new Solicitud();
            solicitud.setIdCliente(idClienteOlder);
            solicitud.setKilogramos(Integer.parseInt(kilogramos.equals("") ? "0" : String.valueOf(Math.round(Float.parseFloat(textoKilogramos.getText())))));
            solicitud.setPrecio(Integer.parseInt(precio.equals("") ? "0" : String.valueOf(Math.round(Float.parseFloat(textoPrecio.getText())))));
            
            daoSolicitud.actualizarSolicitud(idSolicitudOlder, solicitud);

            //actulizar tabla (grilla)
            defaultTableModel.setValueAt(idSolicitudOlder, tablaSolicitud.getSelectedRow(), 0);
            defaultTableModel.setValueAt(idClienteOlder, tablaSolicitud.getSelectedRow(), 1);
            defaultTableModel.setValueAt(nombre, tablaSolicitud.getSelectedRow(), 2);
            defaultTableModel.setValueAt(rut, tablaSolicitud.getSelectedRow(), 3);
            defaultTableModel.setValueAt(email, tablaSolicitud.getSelectedRow(), 4);
            defaultTableModel.setValueAt(direccion, tablaSolicitud.getSelectedRow(), 5);
            defaultTableModel.setValueAt(tipoDomicilio, tablaSolicitud.getSelectedRow(), 6);
            defaultTableModel.setValueAt(ciudad, tablaSolicitud.getSelectedRow(), 7);
            defaultTableModel.setValueAt(kilogramos, tablaSolicitud.getSelectedRow(), 8);
            defaultTableModel.setValueAt(precio, tablaSolicitud.getSelectedRow(), 9);
        }
    }//GEN-LAST:event_botonActualizarSolicitudActionPerformed

    private void botonEliminarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSolicitudActionPerformed
        if(tablaSolicitud.getSelectedRowCount()==1){
            int idSolicitudOlder = Integer.parseInt(defaultTableModel.getValueAt(tablaSolicitud.getSelectedRow(), 0).toString());
            //eliminar desde la base de datos
            daoSolicitud.eliminarSolicitud(idSolicitudOlder);
            //REMOVER FILA DE LA TABLA (grilla)
            defaultTableModel.removeRow(tablaSolicitud.getSelectedRow());

        }
    }//GEN-LAST:event_botonEliminarSolicitudActionPerformed

    private void textoNombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNombreClienteFocusLost
        
    }//GEN-LAST:event_textoNombreClienteFocusLost

    private void textoRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoRutFocusLost
        this.buscarCliente();
    }//GEN-LAST:event_textoRutFocusLost

    private void precioCalculoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCalculoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCalculoTextActionPerformed

    private void ivaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaTextActionPerformed

    private void totalPagarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPagarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPagarTextActionPerformed

    private void textoPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoPrecioFocusLost
        
    }//GEN-LAST:event_textoPrecioFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarSolicitud;
    private javax.swing.JButton botonCrearSolicitud;
    private javax.swing.JButton botonEliminarSolicitud;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JComboBox<Object> comboChofer;
    private javax.swing.JComboBox<Object> comboPlanta;
    private javax.swing.JComboBox<Object> comboResiduo;
    private javax.swing.JComboBox<Object> comboVehiculo;
    private javax.swing.JTextField ivaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precioCalculoText;
    private javax.swing.JTable tablaSolicitud;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoKilogramos;
    private javax.swing.JTextField textoNombreCliente;
    private javax.swing.JTextField textoPrecio;
    private javax.swing.JTextField textoRut;
    private javax.swing.JTextField textoTipoDomicilio;
    private javax.swing.JTextField totalPagarText;
    // End of variables declaration//GEN-END:variables

     private void listarResiduos() {
        Residuo metal = new Residuo("METAL","metal");
        Residuo organico = new Residuo("ORGANICO","Organico");
        Residuo inorganico = new Residuo("INORGANICO","INORGANICO");
        Residuo vidrio = new Residuo("VIDRIO","VIDRIO");
        List<IActivo> residuos = new ArrayList();
        residuos.add(metal);
        residuos.add(organico);
        residuos.add(inorganico);
        residuos.add(vidrio);
        for (IActivo value : residuos) {
            //se agrega al componente grafico combobox de residuos
            Residuo residuo = (Residuo) value;
            comboResiduo.addItem(residuo.getTipo());
        }
    }
    private void listarPlantas() {
        Planta plantaSantiago = new Planta("Planta de Santiago", "Puente alto 15646", "Santiago", 1000);
        Planta plantaValparaiso = new Planta("Planta de Valparaiso", "Puente alto 15646", "Santiago", 2000);
        Planta plantaViñaDelMar = new Planta("Planta de ViñaDelMar", "Puente alto 15646", "Santiago", 3000);
        Planta plantaConcepcion = new Planta("Planta de Concepcion", "Puente alto 15646", "Santiago", 4000);
        List<Planta> plantas = new ArrayList();
        plantas.add(plantaSantiago);
        plantas.add(plantaValparaiso);
        plantas.add(plantaViñaDelMar);
        plantas.add(plantaConcepcion);
        for (Planta value : plantas) {
            //se agrega al componente grafico combobox de plantas
            comboPlanta.addItem(value.getNombrePlana());
        }
    }
    private void listarChoferes() {
        Chofer chofer1 = new Chofer(1, "Jose", "456456-5", "54846546", "correo1@correo.com", "ABCDE", 50000);
        Chofer chofer2 = new Chofer(2, "Jose", "456456-5", "54846546", "correo1@correo.com", "ABCDE", 60000);
        Chofer chofer3 = new Chofer(3, "Jose", "456456-5", "54846546", "correo1@correo.com", "ABCDE", 70000);
        Chofer chofer4 = new Chofer(4, "Jose", "456456-5", "54846546", "correo1@correo.com", "ABCDE", 80000);
        List<AbstractEmpleado> choferes = new ArrayList();
        choferes.add(chofer1);
        choferes.add(chofer2);
        choferes.add(chofer3);
        choferes.add(chofer4);
        for (AbstractEmpleado value : choferes) {
            //se agrega al componente grafico combobox de Choferes
            comboChofer.addItem(value.getNombre());
        }
    }
    private void listarVehiculos() {
        Vehiculo vehiculo1 = new Vehiculo("ABCDEF", "SUV", "suv");
        Vehiculo vehiculo2 = new Vehiculo("ABCDEF", "SEDAN", "suv");
        
        Map<Integer,Vehiculo> vehiculos = new HashMap<Integer, Vehiculo>();
        vehiculos.put(1,vehiculo1);
        vehiculos.put(2,vehiculo2);
        
        for (Map.Entry<Integer, Vehiculo> entry : vehiculos.entrySet()) {
            Vehiculo val = entry.getValue();
            comboVehiculo.addItem(val.getTipoVehiculo());
        }
       
    }
    
    private void limpiarFormulario(){
        textoCiudad.setText("");
        textoDireccion.setText("");
        textoEmail.setText("");
        textoKilogramos.setText("");
        textoNombreCliente.setText("");
        textoPrecio.setText("");
        textoRut.setText("");
        textoTipoDomicilio.setText("");
        
        precioCalculoText.setText("");
        ivaText.setText("");
        totalPagarText.setText("");
    }
    
    private void txfSoloNumeros(java.awt.event.KeyEvent evt,JTextField txf){
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
            (caracter != KeyEvent.VK_BACK_SPACE) &&
            (caracter != '.'))
        {
            evt.consume();  // ignorar el evento de teclado
        }
         if(txf.getText().length()>9)
             evt.consume();
    }
    
    private void listarSolicitudesEnTabla() {
        this.defaultTableModel = new DefaultTableModel(data, cabezera);
        
        ResultSet result = daoSolicitud.listarSolicitudes();
        try { 
            while(result.next()){
                Object[] fila=new Object[cabezera.length];//array sera una de las filas de la tabla
                for(int i=0;i<cabezera.length;i++){          
                    fila[i]=result.getObject(i+1);
                }
                defaultTableModel.addRow(fila);  
            } 
            tablaSolicitud.setModel(defaultTableModel);
        } catch (SQLException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private boolean clienteExiste() {
        String rut = textoRut.getText();
        return daoSolicitud.existeClienteEnSolicitud(rut);
    }
    private boolean solicitudExisteParaCliente() {
        String rut = textoRut.getText();
        //obtener lista
        List<Cliente> clientes = this.listaSolicitudesClientes;
        //recorrer hasta encontrar el objeto cliente
        for (Cliente cliente : clientes) {
            if (cliente.getRutCliente().equals(rut)) {
                return true;
            }
        }
        return false;
    }

    private void buscarCliente() {
        String rut = textoRut.getText();
        //obtener lista
        ResultSet result = clienteDao.obtenerCliente(rut);
        try { 
            if(result.next()){
            String nombreDb = result.getString("nombre"); 
            String emailDb = result.getString("email");
            String direccionDb = result.getString("direccion");
            String tipoDomicilioDb = result.getString("tipo_domicilio");
            String ciudadDb = result.getString("ciudad");
            this.textoNombreCliente.setText(nombreDb);
            this.textoEmail.setText(emailDb);
            this.textoDireccion.setText(direccionDb);
            this.textoTipoDomicilio.setText(tipoDomicilioDb);
            this.textoCiudad.setText(ciudadDb);
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calcularPrecioFinal() {
        String precioCalculo = String.valueOf(Math.round(solicitudSelected.getPrecio()));
        String ivaCalculo = String.valueOf(Math.round(solicitudSelected.obtenerIva()));
        String totalPrecioCalculo = String.valueOf(Math.round(solicitudSelected.obtenerTotalPreciofinal()));
        this.precioCalculoText.setText(precioCalculo);
        this.ivaText.setText(ivaCalculo);
        this.totalPagarText.setText(totalPrecioCalculo);
        
    }

    private void obtenerClienteSelected() {
        String rut = textoRut.getText();
        //obtener lista
        List<Cliente> clientes = this.listaClientes;
        //recorrer hasta encontrar el objeto cliente
        for (Cliente cliente : clientes) {
            if (cliente.getRutCliente().equals(rut)) {
                this.clienteSelected = cliente;
            }
        }
    }

    private void obtenerSolicitudSelected() {
        //un cliente es una fila por cada solicitud que tenga
            Map solicitudes = clienteSelected.getSolicitudes();
            Iterator<String> it = solicitudes.keySet().iterator();
            while (it.hasNext()) {
                Object key =  it.next();
                Integer clave = (Integer) key;
                Solicitud solicitud = (Solicitud) solicitudes.get(clave);
                this.solicitudSelected = solicitud;
            }
    }
}
